### ISSUE TITLE
Create  & Save Attendance Record

### ISSUE THREAD

**Issue by irerimwenda** [kibzsam/sevenhills#5]
- [x] Time in and time out checkout. (use date/time picker)

- [x] Lunch in and lunch out time checkout.

- [x] Successful save to MySQL database.

- [x] Data-table to display records.

- [x] Delete record.

- [x] Calculate the total attendance time for each day that is difference in time in and time out.

- [x] Subtract the lunch time hours taken.

**Comment by irerimwenda** [comment]
Purpose is to create an attendance system to capture each user's records. Time in and out of each day and lunch breaks. Add constraints to limit duplicate entries.

**Comment by kibzsam** [comment]
> Purpose is to create an attendance system to capture each user's records. Time in and out of each day and lunch breaks. Add constraints to limit duplicate entries.
> 
> > ```
> > * [ ]  Time in and time out checkout. (use date/time picker)
> > 
> > * [ ]  Lunch in and lunch out time checkout.
> > 
> > * [ ]  Successful save to MySQL database.
> > 
> > * [ ]  Data-table to display records. (Data table should provide an option to edit the records and                     
> > ```
> 
> ```
>            also delete record)
> ```
> 
> > ```
> > * [ ] should calculate the total attendance time for each day that is difference in time in and time 
> > ```
> 
> ```
>           out subtract the lunch time hours taken
> ```

**Comment by kibzsam** [comment]
You have done a great job so far, however there is some minor adjustment that we need to fix,

1. 
![Screenshot from 2020-05-28 11-03-25](https://user-images.githubusercontent.com/13849712/83115647-5d2d1280-a0d3-11ea-92e7-df5aef3e28b0.png)
Add all the remaining input fields such as lunch in, lunch time out and time out. also the height of the modal popup should be long enough to display time. **The select user dropdown should only display the Authenticated user/employee**

2.
![Screenshot from 2020-05-28 11-03-09](https://user-images.githubusercontent.com/13849712/83116084-f8be8300-a0d3-11ea-82bc-77b8cefc6cf8.png)
3. On this section, (MOST IMPORTANT) thing is that the data table should only show the details for the authenticated employee, no employee should see other employees data, You can add a relationship between the users table and the attendance table where each attendance record will have a user_id, so when you fetch the data you fetch where user_id == authenticated_Id
Also, the calculation of time should happen only after an employee has set the time in and time out, if not the hours worked should read 0 so as to enhance consistency.
4.
![Screenshot from 2020-05-28 11-05-19](https://user-images.githubusercontent.com/13849712/83117478-c9a91100-a0d5-11ea-96d1-bac51bf2b3ef.png)
(Minor fix) The data table should be responsive, also you can add a horizontal scroll bar if the data table is not fully responsive on mobile.

5. Also when a user is creating the attendance **Time In**  for the 1st time before the user accepts, it should prompt them first with a popup modal to confirm if they want to set that time.
